### ISSUE TITLE
Not Wokring! Network error!

### ISSUE THREAD

**Issue by ANDREW-LVIV** [alashow/datmusic#29]
Why Network error!?

**Comment by ANDREW-LVIV** [comment]
Also https://api.datmusic.xyz/search?q=Zinovia
502 Bad Gateway
nginx

**Comment by alashow** [comment]
You shouldn't use api.datmusic.xyz as your backend. You need to deploy your own.

**Comment by ANDREW-LVIV** [comment]
using datmusic-api script?

**Comment by alashow** [comment]
Yes

**Comment by ANDREW-LVIV** [comment]
as I see it wont work on usual hosting?

**Comment by alashow** [comment]
It will. But you will need to learn how Laravel & Lumen works on shared hosting.

**Comment by ANDREW-LVIV** [comment]
Much to learn) Any way I can try it on localhost firstly, correct?

**Comment by alashow** [comment]
Yeah, but you will still need to learn how to install it on localhost.

**Comment by ANDREW-LVIV** [comment]
Ok. Thanks for Feedback!
