### ISSUE TITLE
403 after clicking download link

### ISSUE THREAD

**Issue by pawmel** [alashow/datmusic#31]
![zrzut ekranu 2017-07-23 o 01 17 48](https://user-images.githubusercontent.com/20113449/28495139-e3be7c62-6f44-11e7-98c2-092e14d3f3aa.png)

**Comment by alashow** [comment]
set `true` to `DATMUSIC_MP3_URL_DECODER` in your `.env` file like [this](https://github.com/alashow/datmusic-api/commit/cdba0a56c7e4e57717e5f6df86781f1bba23b5b3).

BTW, open issues like this on [datmusic-api](https://github.com/alashow/datmusic-api).

**Comment by pawmel** [comment]
didn't work, same error :(

**Comment by alashow** [comment]
Can you check storage/logs/datmusic.log when this error occurs?

**Comment by pawmel** [comment]
![zrzut ekranu 2017-07-23 o 13 41 25](https://user-images.githubusercontent.com/20113449/28499031-b04f703a-6fac-11e7-873e-0a5a9c8e00cd.png)

**Comment by pawmel** [comment]
hey,
still can't figure it out, could you please help me?

**Comment by alashow** [comment]
I know this definitely the decoder problem. Are you sure enabled the decoder from . env?

**Comment by pawmel** [comment]
Ok this is weird - it started working somehow and I didn't change anything.
One more thing - where I can remove '.com' from the dl link file?
![zrzut ekranu 2017-07-24 o 22 56 57](https://user-images.githubusercontent.com/20113449/28544446-77501ad8-70c3-11e7-82ad-d9210064d50e.png)

**Comment by alashow** [comment]
Change [`APP_URL`](https://github.com/alashow/datmusic-api/blob/master/.env.example#L5)
