### ISSUE TITLE
403

### ISSUE THREAD

**Issue by pawmel** [alashow/datmusic#32]
Hi,
my url looks like this:
shape-of-you-ed-sheeran.html?q=shape-of-you-ed-sheeranand 
and I got 403.
Can you help me out?
![zrzut ekranu 2017-08-02 o 20 50 55](https://user-images.githubusercontent.com/20113449/28889448-517595ec-77c4-11e7-9609-beca142fdded.png)

**Comment by pawmel** [comment]
I'd like to add that  shape-of-you-ed-sheeran.html? looks identical as index.html file

**Comment by alashow** [comment]
I think you need to setup [cors](https://github.com/alashow/datmusic-api/blob/master/config/cors.php) with your domain.
