### ISSUE TITLE
GET http://localhost:8000/search/search?q=Aloe+Black&page=0 403 (Forbidden) But api is working i checked with postman its working 

### ISSUE THREAD

**Issue by syedmustafa54** [alashow/datmusic#33]
XMLHttpRequest cannot load http://localhost:8000/search/search?q=Aloe+Black&page=0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 403.[](url)

**Comment by alashow** [comment]
See #32
