### ISSUE TITLE
Network error!

### ISSUE THREAD

**Issue by Marty25** [alashow/datmusic#34]
Hello. Why do I get "Network error!" when I try to open html page on my host?

**Comment by syedmustafa54** [comment]
See The Console For More Details 
![screenshot_2](https://user-images.githubusercontent.com/24798263/30060180-deb50b30-925f-11e7-9477-324ff65650fd.png)

**Comment by alashow** [comment]
Yes, watch for the web console to see an error log.

**Comment by alashow** [comment]
It might be related to #35, cors configuration.
