### ISSUE TITLE
I Am having 403 Forbidden. And When i use chrome Unsecure browser the api is working  

### ISSUE THREAD

**Issue by syedmustafa54** [alashow/datmusic#35]
# **# Here is my console error**
![screenshot_2](https://user-images.githubusercontent.com/24798263/30096559-a6e136ce-92f6-11e7-9f11-c0ae3f5dd321.png)
# **# Here is my screenshot where api is working** 
![screenshot_3](https://user-images.githubusercontent.com/24798263/30096574-c29e3eb6-92f6-11e7-957c-b307b575ebc5.png)
# **Here is cors.php file changed to localhost** 
![screenshot_4](https://user-images.githubusercontent.com/24798263/30096591-de51b138-92f6-11e7-8202-1ad7fbe01073.png)
# **Here is my .en file** 
![screenshot_5](https://user-images.githubusercontent.com/24798263/30096597-ea1b4c7c-92f6-11e7-804f-98605513d330.png)

**Comment by alashow** [comment]
I hope you saw `CORS_ALLOWED_ORIGINS` in `.env`. Because that's whats overrides cors.
