### ISSUE TITLE
stream to a player 

### ISSUE THREAD

**Issue by Joseph65** [alashow/datmusic#38]
before i was able to stream to a player with mpv or vlc
but now im getting this error in mpv

mpv https://api.datmusic.xyz/dl/df9f2438/e9b57878
Playing: https://api.datmusic.xyz/dl/df9f2438/e9b57878
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] https: HTTP error 502 Bad Gateway
Failed to open https://api.datmusic.xyz/dl/df9f2438/e9b57878.

Exiting... (Errors when loading file)

i dont think its a bug from mpv or youtube-dl since i have the newest versions.
the same happens with vlc.

**Comment by alashow** [comment]
I had to use some filters to reduce traffic from unknown sources.

Please download the mp3 then play it.
