### ISSUE TITLE
Downloading and Listening made impossible

### ISSUE THREAD

**Issue by Incognito4nonymous** [alashow/datmusic#48]
Hi, it is I again...

I've got an issue again

Whatever file downloaded is 157 bytes in size, and clicking the listen button does nothing... However, the correct size of the files appears upon clicking on the "down" arrow prompting to choose other formats....

Cheers

**Comment by alashow** [comment]
Fixed in https://github.com/alashow/datmusic-api/commit/df677fbd7e8e231a8571450d1770b7ffb6839068

**Comment by Incognito4nonymous** [comment]
Well heck that was fast...
